def generate_bike_recommendation(data):

    budget = data["budget"]

    terrain = data["terrain"]

    if terrain == "trail":

        if budget < 1500:

            return [
                {
                    "brand": "Trek",
                    "model": "Fuel EX 7",
                    "condition": "used"
                },
                {
                    "brand": "Specialized",
                    "model": "Stumpjumper",
                    "condition": "used"
                }
            ]

        return [
            {
                "brand": "YT",
                "model": "Jeffsy Core 2",
                "condition": "new"
            }
        ]

    if terrain == "enduro":

        return [
            {
                "brand": "Santa Cruz",
                "model": "Nomad",
                "condition": (
                    "used"
                    if budget < 2500
                    else "new"
                )
            }
        ]

    if terrain == "downhill":

        return [
            {
                "brand": "Commencal",
                "model": "Supreme DH",
                "condition": (
                    "used"
                    if budget < 3000
                    else "new"
                )
            }
        ]

    return [
        {
            "brand": "Canyon",
            "model": "Spectral",
            "condition": "new"
        }
    ]

def generate_setup(data):

    terrain = data.get(
        "terrain",
        ""
    )

    rider_weight = int(
        data.get(
            "rider_weight",
            75
        )
    )

    fork_pressure = (
        rider_weight * 1.1
    )

    shock_pressure = (
        rider_weight * 2.3
    )

    if terrain == "downhill":

        sag = "30%"

        rebound = "Slow"

        tire_front = "21 PSI"

        tire_rear = "24 PSI"

    elif terrain == "enduro":

        sag = "28%"

        rebound = "Medium"

        tire_front = "22 PSI"

        tire_rear = "25 PSI"

    elif terrain == "trail":

        sag = "25%"

        rebound = "Fast"

        tire_front = "23 PSI"

        tire_rear = "26 PSI"

    else:

        sag = "27%"

        rebound = "Medium"

        tire_front = "22 PSI"

        tire_rear = "25 PSI"

    return {

        "recommended_sag":
            sag,

        "rebound":
            rebound,

        "fork_pressure":
            f"{round(fork_pressure)} PSI",

        "shock_pressure":
            f"{round(shock_pressure)} PSI",

        "front_tire_pressure":
            tire_front,

        "rear_tire_pressure":
            tire_rear,

        "brake_lever_angle":
            "35 degrees",

        "handlebar_rotation":
            "Neutral",

        "notes":
            "Base settings generated by Bike Help AI"
    }